# Generated by Django 2.0.3 on 2018-04-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taste', models.PositiveSmallIntegerField()),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('last_used', models.DateField()),
                ('used_count', models.PositiveIntegerField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
