# Generated by Django 2.0.3 on 2018-05-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='last_used',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meal',
            name='used_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
