language: python
python:
- '3.6'
addons:
- postgresql: '9.5'
env:
- DATABASE_URL=postgres://postgres@localhost/travisdb
before_install:
- export DJANGO_SETTINGS_MODULE=DinDinAPI.settings
- export PYTHONPATH=$HOME/builds/flyiniggle/DinDinAPI
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
script:
- python manage.py migrate
- python manage.py test --pattern="*test.py"
deploy:
  provider: heroku
  app: dindinwebapi
  skip_cleanup: true
  api_key:
    secure: hxRAoTRBqqWGK5prjQWMBg2zKt1qF62rrRLlmfIXIWC01IXiW1+DuJj9ACgRt4BAy0uVEJLhlORj4kdamVA4nuBlcRunh25GyJV3jPs+wS7HUAw/DDjfvZexaoKMOGLzdYyITXEak+ryFAW7sQnQY7JSmkkPKpY4IfIG37VEoG/YPES1gVJq/Fz1laxlJkVWYlqc3+wQ/m521a4oioqRzGvs7d8B5mKVdODsLtz8Q03lo6c9wm5aE2fzpZkrg9xDJ12QEBgkfUrqvFB5B/1hvogCzmRPkmn96xS0PnkFAuy9+cfYK2wnBB4IgX+657Tckfso7kE9ICQfzFCGv7F6nlX+L6cmG9l1qqmuNU+mVB79BYcoDRQKn7ia9lr6x3Y638UF9yzGbUG+U0RGtZm+UlITVaAE3vpzjLhcGfjBSOYTln6RnDuZwEGNZhZeM26lSxh34CoV52JnMxVF8VfoAT0REFj5aJeqnV9DpdIsrKB+Vamkcc8o0opjUkSfoRnA9MUVOHNiJ25hHDAVxOS37NDx+nVDbQPoCRiQIXJuQdnpd039h9nFp9L/BxRZ9y4F2Pbudrw6+sYQ06S6aiQgpq2Oj+LMNdT3iYngyDWlq+JSpy/YeQCdGm17jP10ZuYKV/h3K7Ur/JkE8AfMl7fiMQbiG9ROsGFYOy6+CVdZFaY=
