language: python
python:
- '3.6'
addons:
- postgresql: '9.5'
env:
- DATABASE_URL=postgres://postgres@localhost/travisdb
before_install:
- export DJANGO_SETTINGS_MODULE=DinDinAPI.settings
- export PYTHONPATH=$HOME/builds/flyiniggle/DinDinAPI
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
script:
- python manage.py migrate
- coverage run manage.py test --pattern="*Test.py"
after_success:
- coveralls
deploy:
  - provider: heroku
    api_key:
      secure: ZsOkuEpvibvlMAanpvmvhGeytKRiMlRSQ8kG5Efu00wtmlkPeXaGXllqDRf4HNfEpA896rXJqtaVXAsnmD26ZBVGNKuc5+c3FGBvUiEr2z2iHfMCdqgg7cvb1SmPScikDT/nMgrCcf1fKyvNiHUykM0ceb2ugYRfoQPRwvh0GOwcSoDMXVuB7MKmpbD/JBj9PWxBkIM39wUlC5mTokpHjMQeiLkuhwT/DwjiHJDSg1f3un7ViaYgZ0a42wtESnIyAkzg1nM9XRJBirdPbJU6s/roeM4fbEFZONXuIipoUhTvwZyltXGj6QPdpLcv8h9NEBwag67n4OZA1V+3QSdtJ7gPjlCaYrINtvutuIt+OgbbRF9IagPZ7K5nnFQUtCxuGBkQchT3wRyk6HLLADHvqfFDIaLDA4zq0cB96DVZFwGQjaTaf4sdokkM/gnX6tEyjZlurKY0cc4k4u21F+ID97NHoh49MawTHUovVQy9kM6+cEjqzJ1aHdMi9qF9FUDXB8xMa8QwTgpKEkEYdGNal1d7SqilJnhjqtbSgF2/H4jpqL7mSrGvogfqth1QwuZuhuqxgf4Hj+YdeMe7IR3J/kyk9wQdhl2i2LG1wzuF3kzSnrftxcum2rR+t7PDhb+w5K34OmxWHk+bSoY/Wk37rYlEjRIo7jwVbEWUGsF15dA=
    app: dindinwebapi-staging
    on:
      repo: flyiniggle/DinDinAPI
      branches:
        only:
        - master
        - /^v.*$/
  - provider: heroku
    api_key:
      secure: ZsOkuEpvibvlMAanpvmvhGeytKRiMlRSQ8kG5Efu00wtmlkPeXaGXllqDRf4HNfEpA896rXJqtaVXAsnmD26ZBVGNKuc5+c3FGBvUiEr2z2iHfMCdqgg7cvb1SmPScikDT/nMgrCcf1fKyvNiHUykM0ceb2ugYRfoQPRwvh0GOwcSoDMXVuB7MKmpbD/JBj9PWxBkIM39wUlC5mTokpHjMQeiLkuhwT/DwjiHJDSg1f3un7ViaYgZ0a42wtESnIyAkzg1nM9XRJBirdPbJU6s/roeM4fbEFZONXuIipoUhTvwZyltXGj6QPdpLcv8h9NEBwag67n4OZA1V+3QSdtJ7gPjlCaYrINtvutuIt+OgbbRF9IagPZ7K5nnFQUtCxuGBkQchT3wRyk6HLLADHvqfFDIaLDA4zq0cB96DVZFwGQjaTaf4sdokkM/gnX6tEyjZlurKY0cc4k4u21F+ID97NHoh49MawTHUovVQy9kM6+cEjqzJ1aHdMi9qF9FUDXB8xMa8QwTgpKEkEYdGNal1d7SqilJnhjqtbSgF2/H4jpqL7mSrGvogfqth1QwuZuhuqxgf4Hj+YdeMe7IR3J/kyk9wQdhl2i2LG1wzuF3kzSnrftxcum2rR+t7PDhb+w5K34OmxWHk+bSoY/Wk37rYlEjRIo7jwVbEWUGsF15dA=
    app: dindinwebapi
    on:
      repo: flyiniggle/DinDinAPI
      tags: true
