language: python
python:
- '3.6'
addons:
- postgresql: '9.5'
env:
- DATABASE_URL=postgres://postgres@localhost/travisdb
before_install:
- export DJANGO_SETTINGS_MODULE=DinDinAPI.settings
- export PYTHONPATH=$HOME/builds/flyiniggle/DinDinAPI
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
script:
- python manage.py migrate
- coverage run manage.py test --pattern="*Test.py"
after_success:
- coveralls
deploy:
  - provider: heroku
    api_key:
      secure: Oodx2zOyNR0fga/B+wKF91O0dVrm+aYk4RA0ZhZgsFzGZdnG+der60fk3KNj9ENAAQ+0LYEY+TcFKLplwAl6o/3DJP1Gz/EvIRPDN4hb+ofx/xI0TYaltVBwUPCxkgGrRDRoKyITX4W1slbkMkTVgWMw5z3RQK9aT3IBoRM0xW/4/qrRm6WrFk0hjo5s8PMNSHdDpXAEOrLr16tMhwVLlRfEM1T+CLP1L9TYVm7mABms73Hnj+20DdThKB1yLHI+6aKmhfoV5U3BigzIJ3G/iUzLTBQ3T51+rH3/IbOI+14LX/v0OLE4k6g7hbsOvmBazt2bmQUgVutZNT5vKofATIy+MYhV5c2i5UWRU5MTYdjfvb1883rZGFianIN05YeW1/bcf1P/0RN4KL1co0YP2eC5hTQPQXX5RkF8QaMX3Np9rVqd/auIHO3llNlkFgcaYNlZZNKi2R403aAIG/TZbViF2hpKOsSGqVnVgb4TWWS7xW0NeE9J02VxVnfu+AK+xvGykeZ+VQC+vH6aTDCRp/f55V4aJ4ucuhtiIk0WKoaSrK/wk4+/eUIUYN+aK+8/42SLhoFk4BxBdBG2ONxrWiZGnzucVl3gtWwol+AZRloKmYzih3Nc5viHtodiO2T3sj+suhqPik9eDfx+MSp8jjtKD+u0F5fTbpbSRkh7Gmc=
    app: dindinwebapi-staging
    on:
      repo: flyiniggle/DinDinAPI
      branches:
        only:
        - master
        - /^v.*$/
  - provider: heroku
    api_key:
      secure: NhyKfva8fT5YbsL3rmeojouN2uq7sjb6WVCg+QirL4ZIbR5cSqBW+v8TWBOy7kdVvMDMfBhqiTq7YqvC//lwnzSSwCZh2Rrj3cjHilGqj1PV4195X3DvjjXgWpj+KFCU0wFxUvtTscy9mHChnk+mBQ/rQdRIqaLU4jRNAxWxe1YCUmoeI0InC/W+KOYWmFKPdPK2Rs9tflaU8P6eEbKbLErJR+kxRc6/TqhsJ+k8Ri6GMgy43XIDTy6FqlHHRyO3UgIGb2yY1TP270CoLbR4La7d5kyhj3JHN5AN63JGt641J104KjYfBr13TBch9b+UA+7qVdBLYVfgNwtVMhKRfCnWXbpld/EWOy+ZIHDtvTSjikP8VDnIxiXQwQPyJubihIrj/9d0+fLvL1Fia3nZnBQvMTupl5xeDZ6jFa8ZA28wCW9qZhVO+BvGzpHTfkFTrNJMhh5HRDii5RUBzamJ4sMmm+2DtSZeUzx2zUO9wd4y8EoDK4zImIc0FtCa2ES0Ma7qdXXYvVfO6X6InMP19hWbNt8ZDXmH9mo97QfwAZmyKXrj7gYZm99DxuLTwYYANUKVYkbQ7KxVWnlAsvO7/mARns88f0i88RwBVZIcQ2KhG/msEuUjDAfLV2gT/aQgmql1WjXizyDkzUhsXHe7nXh2CpYpiZjqQfmln3CHyTg=
    app: dindinwebapi
    on:
      repo: flyiniggle/DinDinAPI
      tags: true
