language: python
python:
- '3.6'
addons:
- postgresql: '9.5'
env:
  matrix:
  - DATABASE_URL=postgres://postgres@localhost/travisdb
  global:
    secure: cBUn22Vl2ZuhHjoYqaZFWjfupZ8QcaXUJVaSN2OMmhCZY/utvOMISXs6EQ7mgfgNqfhiEmy3wvPcw8HkYRnRYbah6QK4/IPHdtrzQNduv8Sc/spirIVouWYR+eu2JCaGl0DOwD0OY3G24hZi61QOVb7ixTeqqq09py0dbqIJtmfKMpudBKOYbgormT4GP4YeWeaQ2G6DrDWFSjHuxqY6FbGRh1cGG9GjgZrSp2rCae3n+mhYvdXdkL2+1OdeZtNdoo05urISJ3ArR6q1fh5bY4DHA0Ina1lG4AWc06CB4k+HGpelO06YP9chGaRVrZkDZ1ulaUD2wFZ65yejiK353OvQN43dth9P+yE7HptoJLDIltEyHYLJV1x5EV6FEyQ74dtDmIWxrRsfm068LvNOhh7aP6pW6TAkYWuNzTwv/Dho5Mc3T4d1lwIHwdFfoqm7JFGPyx+tA6nUpZxCmPxsL3BWgpgpaHR3rdZMgzB4GQVSB+0RwVoxT7NmzDhgx0/mVszQsp4EHHOg8ersdBOG6pkwcwcsr8/BQPOPEgzGxq/4NSInyzx0k0DwLJ8pwcyQximmnYvn4VkSiUFkqOGR7q0aDDDP/Phta0Te8ao0Hr0Th90EtJXQjP/ODoQpPkqKIfzf+XzP8jTAWKGDv+jqT7RqE15EPrhDzy0mOO7BuQQ=
before_install:
- export DJANGO_SETTINGS_MODULE=DinDinAPI.settings
- export PYTHONPATH=$HOME/builds/flyiniggle/DinDinAPI
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
script:
- python manage.py migrate
- coverage run manage.py test --pattern="*Test.py"
after_success:
- coveralls
deploy:
  - provider: heroku
    api_key:
      secure: KPAV9XnN8MuwstytStFSLQfAEh3YgzI46uZWdrXWbBBZ8EXj9mku8UNPegFJWYf9qS5WSkCTQ9LhWZ6hG2mzm+PXNbU69BxEXuxqy5mevyx4I/OpPLFcaQyZOEgOXkhfIcS6dW3at3u6udAQfuRupIXYWZuEvzVTx5vOjVToNI9339h4WY8dlb6xUrd4xmDY65jNBKBQ30nRIv0JK/QR8h8A+Jg2Cabz3ejQfOA0cG57cW3JkJY/gZdsCmQSJaSF1sagNAzvA1l83tfBjq0h456ZV0/knDtAS3tM6TJXr6PbHJXNe0HiSd3JuN8iJz4/qkh+sAODrDybGJ6jQzmaGYZ1fMdCpFic9YmQgbdgBOZqypRCvARKuqZHM8JkltN8JQqMxdFuzAcydt8KtA8CC8jGgfSR6SDbOcbqLTNNFATTp+j3gVODA3PhSnx7bTExriwY5GmYkyU256LdT8Pv1T9OVE+WW1+ejk0xwvmsuxK+Zw4zzzpPfHfcNYYnpJiLQaOFMy87tKrId7bHpOoc6ZQiCuZGDgrYOij6LdrOKeo8NuZHmwbP4GDh2QwM/zGGA6u7r5GMz+48ZgB4Qji5ohlEw+VPLRM1WFBct6OOpFNul+lveLq37rF5qjjb3c4tAPlDxshrKm/rYHDXlcaGUY/kVOQJ/CcBvjMkMRH8wpI=
    app: dindinwebapi
    on:
      repo: flyiniggle/DinDinAPI
      tags: true
  - provider: heroku
    api_key:
      secure: KPAV9XnN8MuwstytStFSLQfAEh3YgzI46uZWdrXWbBBZ8EXj9mku8UNPegFJWYf9qS5WSkCTQ9LhWZ6hG2mzm+PXNbU69BxEXuxqy5mevyx4I/OpPLFcaQyZOEgOXkhfIcS6dW3at3u6udAQfuRupIXYWZuEvzVTx5vOjVToNI9339h4WY8dlb6xUrd4xmDY65jNBKBQ30nRIv0JK/QR8h8A+Jg2Cabz3ejQfOA0cG57cW3JkJY/gZdsCmQSJaSF1sagNAzvA1l83tfBjq0h456ZV0/knDtAS3tM6TJXr6PbHJXNe0HiSd3JuN8iJz4/qkh+sAODrDybGJ6jQzmaGYZ1fMdCpFic9YmQgbdgBOZqypRCvARKuqZHM8JkltN8JQqMxdFuzAcydt8KtA8CC8jGgfSR6SDbOcbqLTNNFATTp+j3gVODA3PhSnx7bTExriwY5GmYkyU256LdT8Pv1T9OVE+WW1+ejk0xwvmsuxK+Zw4zzzpPfHfcNYYnpJiLQaOFMy87tKrId7bHpOoc6ZQiCuZGDgrYOij6LdrOKeo8NuZHmwbP4GDh2QwM/zGGA6u7r5GMz+48ZgB4Qji5ohlEw+VPLRM1WFBct6OOpFNul+lveLq37rF5qjjb3c4tAPlDxshrKm/rYHDXlcaGUY/kVOQJ/CcBvjMkMRH8wpI=
    app: dindinwebapi-staging
    on:
      repo: flyiniggle/DinDinAPI
      branch: master