language: python
python:
- '3.6'
addons:
- postgresql: '9.5'
env:
- DATABASE_URL=postgres://postgres@localhost/travisdb
before_install:
- export DJANGO_SETTINGS_MODULE=DinDinAPI.settings
- export PYTHONPATH=$HOME/builds/flyiniggle/DinDinAPI
- export PIP_USE_MIRRORS=true
install:
- pip install -r requirements.txt
before_script:
- psql -c "CREATE DATABASE travisdb;" -U postgres
script:
- python manage.py migrate
- coverage run manage.py test --pattern="*Test.py"
after_success:
- coveralls
deploy:
  - provider: heroku
    api_key:
      secure: HE+QQNb2Jb1RJDvZVrTC2JcsFcPjJ3Kmfd0qNKNuTct4mbmpJuR/AWVxpTeNyb1EWehErARR6S6Au+JuRw83eX+heSYaK2NCrkWyDRun6BsrpYR2mMHgJHN03mh2KPYOKJiXkIGwJREskojH0xUn7aJjCCH9FUiBBpEapwC/nrnWecux3pqyAkoZffRiyCNd6Go/B7vOMntiSmHyY1nYsIR7uxmfcTcqCgs9qVjO5ZyzRbV9As65/t4+KPhfBQD7Ph3r49x+jaj6Ct1Dj1n96da1kjnoBpfY+nE/5QqvLQD63UsoIBQQx1Q5O5D39Ie3AHr6l7qZoXAAp9zZyCPWk9nVrjfqo+I+OHHD0XS2Y+mEXN/XY8vGv/8VquPbqmGtGo9dA+o4aFvQaEAQYXPb+MgwZYzqfP/nGb0hkTJSR26zmH3mxJL0ND5PJS6Sr28za5LvhGeGASPUD126cLaSH+WSX6hYQyfSoYpjta5xRs8idngTuQ+/16+FZqKWIXvGD84ju60P6iidV9/xIriPjiJ740GGsVKUuDpnE4thU1uLSrrtCx5El209d5a4yEh5pV45332/2oyvNN1njreUphGyXu3apquRKzbPwpgCPk3bfe6KLbXHtRwnvuyd9pbKJJRF5PzWKlSZSDEqPFfpK4hHvu7g/TgqYZdiPtAgASI=
    app: dindinwebapi-staging
    on:
      repo: flyiniggle/DinDinAPI
      branches:
        only:
        - master
        - /^v.*$/
  - provider: heroku
    api_key:
      secure: hp9xktuKDgWc7M/Tzb/Qut+Dd+/nsGxgSNySeGep8su8C2ZUWddVs7BAEPLBaMrNZM93wU8iqwl0RCsFL/Ja/qkZsCDUMkxQOPbKa64Qubb4treKgge4tx4XQuwOm+wP5ma7OXeOUODiTCn6vMil6nAEPr+sH/BdpW+gF6/qtEZGkfavpOKv0eSvNMRqCN77O+4nv35ZIaqMhGGyPWtTkXn8NYxNu8Yc/r3ZHziYr5eBceMGEcrU5+94EwUZlYiC7kkLsfnRQu6UhXzIqPORT8h0Br7fgrpFv4rIQKBZpRK0Fo/ifMZD0qRE8nnAIuTrHq2wAoq2fFHXsQj7JVxrnPjsga8rQBrxOcYUQSM4eQ/FwevC7yqfmSWMcHBWWNuoCDy0/sFeUSzxmeYZuGnmdY7n4yFWyekrek9d3A12w0jTUZltHqFQwtYI96wcksp5/66nRi/XA1j1CvDWc5s8ltpjnY+OgPtdTWIEfKn/MewvYjTIzzl2Yn3q7wDxo89yujdDaKk0gRoGMKAIku2O1OY7lUYFYncmjbWvRNuzZhc3NZm+oHtiog8gjOOJM1rJxWRG4HG/rqFVH0phPCo+KuKY+U0J6+rC0hM/Y8he5rBwnKe4Z9P/TwLxevD8veGa7mkQ1Ra4pERERwGU7bM/jCidmzwFii+EjHg5li61Vak=
    app: dindinwebapi
    on:
      repo: flyiniggle/DinDinAPI
      tags: true
