# Generated by Django 2.0.3 on 2018-05-20 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0005_auto_20180519_1615'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCollaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_shared_meal', to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_collaborator', to='meals.Meal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_collaboration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
