# Generated by Django 2.0.3 on 2018-05-23 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingcollaboration',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_shared_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingcollaboration',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_collaborations', to=settings.AUTH_USER_MODEL),
        ),
    ]
